server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'

  - job_name: aggregator
    static_configs:
      - targets:
          - localhost
        labels:
          job: aggregator
          service: aggregator-app
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
            level: attrs.level
            msg: log
            component: attrs.component
            target: attrs.target

      - labels:
          stream:
          tag:
          level:
          component:
          target:

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: msg