global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Aggregator metrics
  - job_name: 'aggregator'
    static_configs:
      - targets: ['aggregator:9000']  # Docker service name
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 3s

  # Node exporter (optional - for system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 